FROM alpine

RUN apk update
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip

COPY ./requirements.txt /requirements.txt
RUN pip3 install -r /requirements.txt
RUN pip3 install --upgrade google-api-python-client

COPY ./gRPC/rpi_client.py /grpc/rpi_client.py
COPY ./gRPC/rpi_pb2_grpc.py /grpc/rpi_pb2_grpc.py
COPY ./gRPC/rpi_pb2.py /grpc/rpi_pb2.py

EXPOSE 50051
