# This is for generating model on server
FROM jupyter/scipy-notebook

VOLUME D:/Git Repos/3004_G25_Smart_Home_Automation

RUN pip install joblib

COPY toPredict.csv ./toPredict.csv

COPY predictClass.py ./predictClass.py

RUN python3 predictClass.py