# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpi.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trpi.proto\x12\x03rpi\")\n\x07Request\x12\x10\n\x08roomName\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"\x14\n\x05Reply\x12\x0b\n\x03res\x18\x01 \x01(\t24\n\x03RPI\x12-\n\x0fprocessRoomData\x12\x0c.rpi.Request\x1a\n.rpi.Reply\"\x00\x62\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_REPLY = DESCRIPTOR.message_types_by_name['Reply']
Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'rpi_pb2'
  # @@protoc_insertion_point(class_scope:rpi.Request)
  })
_sym_db.RegisterMessage(Request)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), {
  'DESCRIPTOR' : _REPLY,
  '__module__' : 'rpi_pb2'
  # @@protoc_insertion_point(class_scope:rpi.Reply)
  })
_sym_db.RegisterMessage(Reply)

_RPI = DESCRIPTOR.services_by_name['RPI']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=18
  _REQUEST._serialized_end=59
  _REPLY._serialized_start=61
  _REPLY._serialized_end=81
  _RPI._serialized_start=83
  _RPI._serialized_end=135
# @@protoc_insertion_point(module_scope)
