FROM alpine

RUN apk update
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip

RUN pip3 install sense-hat

COPY ../gRPC/sensorLogger.py /grpc/sensorLogger.py
